Add ISSUER variable to central OPA deployment
DiamondLightSource/authz pull request #200
Opened 2024-11-01 16:18 UTC by tpoliaw

2024-11-01 16:26 UTC, garryod commented
We should probably use the OIDC discovery endpoint to get these, see: https://openid.net/specs/openid-connect-discovery-1_0.html

2024-11-13 17:17 UTC, tpoliaw commented
From the OPA docs [here](https://www.openpolicyagent.org/docs/latest/oauth-oidc/#metadata-discovery) it looks like we should be setting ISSUER but not JWKS_ENDPOINT

2024-11-14 10:27 UTC, garryod requested changes

2024-11-14 10:27 UTC, garryod commented on charts/opa/Chart.yaml
> +version: 0.5.1
This should be a breaking change (`0.6.0`)

2024-11-14 10:27 UTC, garryod commented on policy/diamond/policy/token/token.rego
> +		"url": concat("", [issuer, "/.well-known/openid--configuration"]),
We should pass in the well known URL and retrieve the `issuer` from there, as the path of the well-known endpoint isn't guaranteed to be `/.well-known/openid-configuration`

2024-11-14 10:27 UTC, garryod commented on policy/diamond/policy/token/token.rego
> +		"url": concat("", [issuer, "/.well-known/openid--configuration"]),
Not sure the double hyphen is correct

2024-11-14 15:42 UTC, garryod commented on policy/diamond/policy/token/token.rego
> +		"url": concat("", [issuer, "/.well-known/openid--configuration"]),
Oh, fair enough then. Swear I've seen it be something else but can't figure out where

2024-11-14 15:43 UTC, garryod submitted a review, later dismissed

2024-11-14 15:51 UTC, garryod approved these changes

2024-11-14 15:52 UTC, garryod commented
> Sorry, found a docs change I missed in the final read through

No worries, much preferred to finding it six months from now

2024-11-14 15:56 UTC, merged