Add github actions for rego files
DiamondLightSource/authz pull request #9
Opened 2023-12-11 16:32 UTC by DiamondJoseph

- Test and lint rego files in org-policy directory on pushing to github
- Build and publish OCI Bundle when tag created on github
- Add OPA plugin to devcontainer

2023-12-12 15:41 UTC, DiamondJoseph commented
I'm uncertain if the Policy release will occur when making a tag

2023-12-12 16:07 UTC, garryod requested changes

2023-12-12 16:07 UTC, garryod commented on .github/workflows/policy-release.yml
Can we rename this file to be consistent with the bundler one?

2023-12-12 16:07 UTC, garryod commented on .github/workflows/policy-release.yml
> +      - main
We want to run the CI on every push, just not do the upload

2023-12-12 16:07 UTC, garryod commented on .github/workflows/policy-release.yml
> +        run: oras push ${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }} --config ./org-policy/config.json:application/vnd.oci.image.config.v1+json bundle.tar.gz:application/vnd.oci.image.layer.v1.tar
Should add an `if` here that is similar to the one on in `bundler-container`, e.g.:
```
${{ !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) }}
```

2023-12-12 16:07 UTC, garryod commented on .github/workflows/policy-release.yml
> +        uses: open-policy-agent/setup-opa@v2
Would rather use a fully qualified version number

2023-12-12 16:07 UTC, garryod commented on .github/workflows/policy-test.yml
> +        uses: open-policy-agent/setup-opa@v2
Would rather use a fully qualified version number

2023-12-13 10:40 UTC, garryod approved these changes
LGTM, any chance you could squash the commits down some before merging?

2023-12-13 15:09 UTC, garryod approved these changes

2023-12-13 15:09 UTC, merged